<a href="https://colab.research.google.com/github/mirandoli/Jupyter-Tutoriais/blob/master/Desafio_mod2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                                        **Desafio Módulo 2 MPT**

In [ ]:
# BBTS
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
# Importando o arquivo para o colab
from google.colab import files
uploaded = files.upload()

Saving winequality-red.csv to winequality-red (12).csv


In [ ]:
# lendo os dados 
df_winequali = pd.read_csv('winequality-red.csv', sep=';')

In [ ]:
print(type(df_winequali))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
# Visualização do dataset
df_winequali.head(10)

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5
5            7.4              0.66         0.00  ...       0.56      9.4        5
6            7.9              0.60         0.06  ...       0.46      9.4        5
7            7.3              0.65         0.00  ...       0.47     10.0        7
8            7.8              0.58         0.02  ...       0.57      9.5        7
9            7.5              0.50         0.36  ...       0.80     10.5        5

[10 rows x 12 columns]

In [ ]:
print('O mínimo quality é: {}'.format(min(df_winequali['quality'])))
print('O máximo quality é: {}'.format(max(df_winequali['quality'])))


O mínimo quality é: 3
O máximo quality é: 8


In [ ]:
# Contando o número de ocorrência de cada tipo de qualidade
df_winequali['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [ ]:
# Shape do dataset
df_winequali.shape

(1599, 12)

In [ ]:
# Informações do dataset
df_winequali.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
# Verificando a existência de valores nulos
df_winequali.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
# Descrição estatística do dataset
df_winequali.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

**Preparação dos dados:**

In [ ]:
entradas = df_winequali[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides',	'free sulfur dioxide',	'total sulfur dioxide',	'density',	'pH',	'sulphates',	'alcohol']]
from sklearn.preprocessing import MinMaxScaler # Normalização dos dados
scaler = MinMaxScaler() #scaler = MinMaxScaler(feature_range=(0, 1)) # Dados normalizados ficarão entre 0 e 1 
entradas_normalizadas = scaler.fit_transform(entradas.values)

In [ ]:
print(type(df_winequali))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
# Qual é o menor valor para a variável "fixed acidity"?
print(entradas_normalizadas.min())
print(entradas_normalizadas.max())


0.0
1.0000000000000002


In [ ]:
# Dividindo os dados entre treinamento e teste
saida = df_winequali['quality'].values.reshape(-1,1)
print('Tipo saída: ',type(saida))
print('Entradas: ' ,entradas_normalizadas.shape)
print('Saídas: ',saida.shape)

Tipo saída:  <class 'numpy.ndarray'>
Entradas:  (1599, 11)
Saídas:  (1599, 1)


In [ ]:
# Divisão dos dados para treinamento e teste
x_train, x_test, y_train, y_test = train_test_split(entradas_normalizadas, saida, test_size=0.30, random_state=1)

**KNN**

In [ ]:
# Importando as bbts
import pylab as pl # Plotar os gráficos
from sklearn import neighbors, datasets

In [ ]:
# Treinamento do modelo
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5) # 5 vizinhos mais próximos
classifier.fit(x_train, y_train) # realiza a classificação

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
# Previsão
y_pred = classifier.predict(x_test)

In [ ]:
# Matriz para verificação da acurácia e demais parâmetros
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  1   0   1   0   0   0]
 [  0   1  14   5   1   0]
 [  0   0 148  54   5   0]
 [  0   1  71 102  21   0]
 [  0   1   9  23  19   0]
 [  0   0   0   1   2   0]]
              precision    recall  f1-score   support

           3       1.00      0.50      0.67         2
           4       0.33      0.05      0.08        21
           5       0.61      0.71      0.66       207
           6       0.55      0.52      0.54       195
           7       0.40      0.37      0.38        52
           8       0.00      0.00      0.00         3

    accuracy                           0.56       480
   macro avg       0.48      0.36      0.39       480
weighted avg       0.55      0.56      0.55       480



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**ÁRVORE DE DECISÃO**

In [ ]:
from sklearn.tree import DecisionTreeClassifier # importa o classificador árvore de decisão
from sklearn import metrics # importa as métricas para avaliação

In [ ]:
# Objeto de classificação 
clf = DecisionTreeClassifier()

# Treinamento
clf = clf.fit(x_train, y_train)

# Previsão da classificação
y_pred_tree = clf.predict(x_test)

In [ ]:
# Matriz para verificação da acurácia e demais parâmetros para ÁRVORE DE DECISÃO
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred_tree))

[[  1   0   1   0   0   0]
 [  0   1  14   5   1   0]
 [  0   0 148  54   5   0]
 [  0   1  71 102  21   0]
 [  0   1   9  23  19   0]
 [  0   0   0   1   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.12      0.10      0.11        21
           5       0.67      0.71      0.69       207
           6       0.65      0.54      0.59       195
           7       0.43      0.60      0.50        52
           8       0.20      0.33      0.25         3

    accuracy                           0.60       480
   macro avg       0.34      0.38      0.36       480
weighted avg       0.61      0.60      0.60       480



**RANDOM FOREST**

In [ ]:
# Importando as bbts
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Treinamento
rf_clf = RandomForestClassifier(n_estimators=400, n_jobs=-1, random_state=1)
rf_clf.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=400,
                       n_jobs=-1, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [ ]:
# Previsão 
y_pred_rf = rf_clf.predict(x_test)

In [ ]:
# Matriz para verificação da acurácia e demais parâmetros para RANDOM FOREST
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred_rf))

[[  1   0   1   0   0   0]
 [  0   1  14   5   1   0]
 [  0   0 148  54   5   0]
 [  0   1  71 102  21   0]
 [  0   1   9  23  19   0]
 [  0   0   0   1   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        21
           5       0.71      0.83      0.76       207
           6       0.68      0.67      0.67       195
           7       0.57      0.46      0.51        52
           8       0.50      0.33      0.40         3

    accuracy                           0.68       480
   macro avg       0.41      0.38      0.39       480
weighted avg       0.65      0.68      0.66       480



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**SVM**

In [ ]:
# Importando as bbts
from sklearn.svm import SVC

In [ ]:
# Objeto SVM
svc_clf = SVC(gamma='auto') 

In [ ]:
# Treinamento
svc_clf.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
# Previsão
y_pred_svc = svc_clf.predict(x_test)

In [ ]:
# Matriz para verificação da acurácia e demais parâmetros para RANDOM FOREST
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred_svc))

[[  1   0   1   0   0   0]
 [  0   1  14   5   1   0]
 [  0   0 148  54   5   0]
 [  0   1  71 102  21   0]
 [  0   1   9  23  19   0]
 [  0   0   0   1   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        21
           5       0.61      0.86      0.71       207
           6       0.55      0.53      0.54       195
           7       0.00      0.00      0.00        52
           8       0.00      0.00      0.00         3

    accuracy                           0.59       480
   macro avg       0.19      0.23      0.21       480
weighted avg       0.49      0.59      0.53       480



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**MLP**

In [ ]:
# Importando as bbts
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input, Dropout
from tensorflow.keras.optimizers import SGD
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
# Objeto MLP
clf_MLP =  MLPClassifier(alpha=1e-5, hidden_layer_sizes=(5, 5), random_state=1)

In [ ]:
# TREINAMENTO
clf_MLP.fit(x_train,y_train)             
   
y_pred_MLP = clf_MLP.predict(x_test)
accuracy_score_MLP = accuracy_score(y_test, y_pred_MLP)
print('accuracy_score: %.2f \n' %accuracy_score_MLP)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


accuracy_score: 0.60 



/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [ ]:
# Camada de entrada Entradas:  (1599, 11) Saídas:  (1599, 1)
camada_entrada = Input(shape=(1599, 11,), dtype='float32')

In [ ]:
# Camadas escondidas
densa1 = Dense(32, activation='linear')(camada_entrada)
densa2 = Dense(16, activation='linear')(densa1)
densa3 = Dense(16, activation='linear')(densa2)

In [ ]:
# Camada de dropout para evitar overfitting
camada_dropout = Dropout(0.2)(densa3)

In [ ]:
# Camada de saída
camada_saida = Dense(1,activation='linear')(camada_dropout)

In [ ]:
# Definação do modelo MLP
modelo_MLP = tf.keras.Model(inputs=camada_entrada, outputs=camada_saida)

In [ ]:
# Características do modelo
modelo_MLP.summary()

Model: "model_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 1599, 11)]        0         
_________________________________________________________________
dense_38 (Dense)             (None, 1599, 32)          384       
_________________________________________________________________
dense_39 (Dense)             (None, 1599, 16)          528       
_________________________________________________________________
dense_40 (Dense)             (None, 1599, 16)          272       
_________________________________________________________________
dropout_9 (Dropout)          (None, 1599, 16)          0         
_________________________________________________________________
dense_41 (Dense)             (None, 1599, 1)           17        
Total params: 1,201
Trainable params: 1,201
Non-trainable params: 0
_________________________________________________________

In [ ]:
# Otimizador a ser utilizado e função de erro
modelo_MLP.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
# Treinamento MLP
modelo_MLP.fit(x=x_train, y=y_train, batch_size=10, epochs=20, verbose=1, shuffle=True)

Epoch 1/20
112/112 [==============================] - 0s 2ms/step - loss: 8.8901
Epoch 2/20
112/112 [==============================] - 0s 2ms/step - loss: 1.7287
Epoch 3/20
112/112 [==============================] - 0s 2ms/step - loss: 1.4419
Epoch 4/20
112/112 [==============================] - 0s 2ms/step - loss: 1.2192
Epoch 5/20
112/112 [==============================] - 0s 2ms/step - loss: 1.2177
Epoch 6/20
112/112 [==============================] - 0s 2ms/step - loss: 1.1222
Epoch 7/20
112/112 [==============================] - 0s 2ms/step - loss: 1.0698
Epoch 8/20
112/112 [==============================] - 0s 2ms/step - loss: 1.0653
Epoch 9/20
112/112 [==============================] - 0s 2ms/step - loss: 1.0427
Epoch 10/20
112/112 [==============================] - 0s 2ms/step - loss: 0.9801
Epoch 11/20
112/112 [==============================] - 0s 2ms/step - loss: 0.9463
Epoch 12/20
112/112 [==============================] - 0s 2ms/step - loss: 0.9750
Epoch 13/20
112/112 [====

In [ ]:
# Previsão
y_pred_MLP = modelo_MLP.predict(x_test)

**TRANSFORMANDO O DATASET PARA O SISTEMA BINÁRIO**

In [ ]:
clf_quality = {'bom': 6, 7, 8, 
               'ruim':5, 4, 3}
df_winequali['quality'] = df_winequali(clf_quality, columns=['quality'])

SyntaxError: ignored